INSERT INTO `faq` (`id`, `title`, `content`, `created_at`, `updated_at`) VALUES (NULL, 'È possible eliminare il mio profilo?', 'Attualmente l’unico modo per far si che il tuo profilo venga completamente eliminato dal sito è contattare un amministratore. Ma non esitare, sono disponibili e molto veloci nella risposta!', current_timestamp(), current_timestamp());

INSERT INTO `faq` (`id`, `title`, `content`, `created_at`, `updated_at`) VALUES (NULL, 'Quante recensioni posso lasciare?', 'Non vi è alcun limite in vigore se non quello dettato dal buon senso, aiuta gli altri utenti a sapere di più del telefono con quante recensioni ritieni necessario! Ricorda: non esagerare.', current_timestamp(), current_timestamp());

INSERT INTO `faq` (`id`, `title`, `content`, `created_at`, `updated_at`) VALUES (NULL, 'È possibile modificare le informazioni relative al mio profilo?', 'Semplicemente recandoti nella pagina profilo , hai a disposizioni alcune informazioni modificabili quali: nome e cognome. Per motivi di autenticazione non ti è concesso cambiare la mail e la password.', current_timestamp(), current_timestamp());

INSERT INTO `faq` (`id`, `title`, `content`, `created_at`, `updated_at`) VALUES (NULL, 'Chi può vedere le mie recensioni?', 'Essendo l’obbiettivo del sito quello di fornire chiarezza e consigli da parte degli utenti che hanno realmente maneggiato il cellulare in questione, le recensioni lasciate da qualsiasi utente sono visibili a tutti.', current_timestamp(), current_timestamp());

INSERT INTO `faq` (`id`, `title`, `content`, `created_at`, `updated_at`) VALUES (NULL, 'È possibile modificare un voto che ho lasciato?', 'Il nostro sito ha preso in considerazione la possibilità che un telefono possa non suscitare lo stesso effetto a distanza di qualche giorno. Per questo motivo ti è concesso non solo cambiare il voto che hai lasciato, ma anche eliminare e modificare un commento!', current_timestamp(), current_timestamp());

INSERT INTO `faq` (`id`, `title`, `content`, `created_at`, `updated_at`) VALUES (NULL, 'Chi si occupa dell’inserimento dei telefoni e dei dettagli?', 'Per poter garantire affidabilità nelle informazioni fornite, l’inserimento di un dispositivo mobile e i dettagli ad esso associati vengono inseriti da un team di amministratori preparati in materia. Nel caso in cui volessi farne parte o ritieni manchi qualche telefono puoi contattarci! Prenderemo in seria considerazione la tua proposta.', current_timestamp(), current_timestamp());